baseurl = "/" 
languageCode = "en-us"
title = "StatPREP 101" 
publishDir = "public"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Topics"
    url = "/topics/"
    weight = 1
[[menu.main]]
    name = "Activities"
    url = "/lessons/"
    weight  = 4
[[menu.main]]
    name = "LittleApps"
    url = "/littleapps/"
    weight = 10
[[menu.main]]
    name = "Suggestions?"
    url = "https://docs.google.com/document/d/1F76ypB785RyA_CAedEITXrs__hQj2pvbtSaLwD3b31k/edit?usp=sharing"
    weight = 15
[[menu.main]]
    name = "+"
    url = "/etc/" 
    weight = 20


[params]
    description = "StatPREP 101"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "StatPREP-lessons.png"
    width = 50
    height = 50
    alt = "Logo"

